services:
  arktech-website:
    image: arkapravoghosh1/arktech-website:latest
    container_name: arktech-website
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - arktech-certs:/etc/nginx/certs/
    networks:
      - arktech-network

volumes:
  arktech-certs:
    external: true
    name: arktech-certs

networks:
  arktech-network:
    driver: bridge
